stages:
    - test
    - coverage
    - package
    - update_repo

linter:
    image: daedalusproject/base_bash_utils:201904300501
    stage: test
    script:
        - shellcheck lib/*.sh

unit_tests:
    image: daedalusproject/base_bash_utils:201904300501
    stage: test
    before_script:
        - apt-get update
        - echo percona-server-server  percona-server-server/root-pass password letmein | debconf-set-selections
        - echo percona-server-server  percona-server-server/re-root-pass password letmein | debconf-set-selections
        - echo percona-server-server  percona-server-server/default-auth-override select 1 | debconf-set-selections
        - apt-get install -y percona-server-server
    script:
        - make test

cover:
    image: daedalusproject/base_bash_utils:201904300501
    stage: coverage
    script:
        - make cover
    coverage: /Coverage:\ (\d+\.\d+?)%$/
    artifacts:
        paths:
        - coverage
        expire_in: 15 minutes
