stages:
    - linter
    - test
    - coverage
    - package
    - update_repo

linter:
    image: daedalusproject/base_bash_utils:201904300501
    stage: test
    script:
        - shellcheck lib/*.sh

unit_tests:
    image: daedalusproject/base_bash_utils:201904300501
    stage: test
    script:
        - make test

cover:
    image: daedalusproject/base_bash_utils:201904300501
    stage: coverage
    script:
        - make cover
    coverage: /Coverage:\ (\d+\.\d+?)%$/
    artifacts:
        paths:
        - coverage
        expire_in: 15 minutes
