stages:
    - linter
    - set_test_environment
    - test
    - set_coverage_environment
    - coverage
    - package
    - update_repo

linter:
    image: daedalusproject/base_bash_utils:201905011523
    stage: linter
    script:
        - shellcheck lib/*.sh

deploy_databse:
    image: daedalusproject/base_kubectl:201905011523
    stage: set_test_environment
    script:
        - declare -a -g REQUIRED_VARIABLES
        - REQUIRED_VARIABLES=( 'KUBERNETES_URL' 'KUBERNETES_USER_NAME' 'KUBERNETES_USER_TOKEN')
        - source utils/create_environment.sh
        - delete_config
        - create_config

unit_tests:
    image: daedalusproject/base_bash_utils:201905011523
    stage: test
    script:
        - make test

deploy_databse_for_coverage:
    image: daedalusproject/base_kubectl:201905011523
    stage: set_coverage_environment
    script:
        - declare -a -g REQUIRED_VARIABLES
        - REQUIRED_VARIABLES=( 'KUBERNETES_URL' 'KUBERNETES_USER_NAME' 'KUBERNETES_USER_TOKEN')
        - source utils/create_environment.sh
        - delete_config
        - create_config


cover:
    image: daedalusproject/base_bash_utils:201905011523
    stage: coverage
    script:
        - make cover
    coverage: /Coverage:\ (\d+\.\d+?)%$/
    artifacts:
        paths:
        - coverage
        expire_in: 15 minutes
