stages:
    - linter
    - set_test_environment
    - test
    - set_coverage_environment
    - coverage
    - package
    - update_repo

linter:
    image: daedalusproject/base_bash_utils:201905041029
    stage: linter
    script:
        - shellcheck --exclude=SC2086 --exclude=SC2034 lib/*.sh

deploy_databse:
    image: daedalusproject/base_kubectl:201905041029
    stage: set_test_environment
    script:
        - declare -a -g REQUIRED_VARIABLES
        - REQUIRED_VARIABLES=( 'KUBERNETES_URL' 'KUBERNETES_USER_NAME' 'KUBERNETES_USER_TOKEN')
        - source utils/create_environment.sh
        - create_kube_config
        - delete_configs
        - create_configs

unit_tests:
    image: daedalusproject/base_bash_utils:201905041029
    stage: test
    before_script:
        - sudo apt-get update
        - sudo apt-get install -y percona-server-client
    script:
        - make test

deploy_databse_for_coverage:
    image: daedalusproject/base_kubectl:201905041029
    stage: set_coverage_environment
    script:
        - declare -a -g REQUIRED_VARIABLES
        - REQUIRED_VARIABLES=( 'KUBERNETES_URL' 'KUBERNETES_USER_NAME' 'KUBERNETES_USER_TOKEN')
        - source utils/create_environment.sh
        - create_kube_config
        - delete_configs
        - create_configs


cover:
    image: daedalusproject/base_bash_utils:201905041029
    stage: coverage
    before_script:
        - sudo apt-get update
        - sudo apt-get install -y percona-server-client
    script:
        - make cover
    coverage: /Coverage:\ (\d+\.\d+?)%$/
    artifacts:
        paths:
        - coverage
        expire_in: 15 minutes

create_deb_package:
    image: daedalusproject/base_deb_builder:201905041029
    stage: package
    script:
        - DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -uc -b
        - mkdir package
        - mv ../daedalus-project-mysql-utils*.deb package/
    artifacts:
        paths:
        - package
        expire_in: 15 minutes
