#!/bin/bash -
#===============================================================================
#
#          FILE: get_coverage
# 
#         USAGE: get_coverage.sh TEST_FOLDER
# 
#   DESCRIPTION: Calculates coverage
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Álvaro Castellano Vela (alvaro.castellano.vela@gmail.com)
#  ORGANIZATION: Daedalus Project
#       CREATED: 04/26/2019 16:52
#      REVISION: 0.1
#===============================================================================

set -o nounset                              # Treat unset variables as an error

TEST_FOLDER=$1

COVERAGE="0%"

for testfile in $(ls $TEST_FOLDER/*-test_*.sh)
do
    COVERAGE=$(bashcov -- $testfile | tail -n 1 | grep -oh "[0-9]\+\.[0-9]*%")
done

echo "Coverage: $COVERAGE"
