---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-test
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: mysql-test
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: 200Mi
    limits.cpu: "200m"
    limits.memory: 200Mi
    pods: "3"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-mysql-test-runner
  namespace: mysql-test
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-daedalus-project-deployer
  namespace: mysql-test
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-mysql-test-runner
  namespace: mysql-test
subjects:
- kind: ServiceAccount
  name: gitlab-mysql-test-runner
  namespace: mysql-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-mysql-test-runner
---
