apiVersion: v1
kind: Pod
metadata:
  name: percona-server
  namespace: mysql-test
  labels:
    app: percona-server
    tier: bakend
    environment: test
spec:
  containers:
  - name: percona-server
    image: daedalusproject/base_percona_server:201905041029
    ports:
    - containerPort: 3306
    lifecycle:
      postStart:
        exec:
          command:
            - "sh"
            - "-c"
            - >
              while [ ! -S /var/run/mysqld/mysqld.sock ];
              do
              sleep 2 ;
              done ;
              /usr/bin/mysql -uroot -pletmein -Bse "CREATE USER 'root'@'%' IDENTIFIED BY 'letmein';";
              /usr/bin/mysql -uroot -pletmein -Bse "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION";
---
apiVersion: v1
kind: Service
metadata:
  name: percona-server
  namespace: mysql-test
  labels:
    app: percona-server
    environment: test
    tier: bakend
spec:
  ports:
  - name: access
    port: 3306
  selector:
    app: percona-server
    tier: bakend
    environment: test
