apiVersion: v1
kind: Pod
metadata:
  name: percona-server
  namespace: mysql-test
  labels:
    app: percona-server
    tier: bakend
    environment: test
spec:
  containers:
  - name: percona-server
    image: daedalusproject/base_develop_percona_server
    ports:
    - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: percona-server
  namespace: mysql-test
  labels:
    app: percona-server
    environment: test
    tier: bakend
spec:
  ports:
  - name: access
    port: 3306
  selector:
    app: percona-server
    tier: bakend
    environment: test
